# Generated by Django 3.1.5 on 2021-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('loction', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('img_one', models.ImageField(upload_to='pics/')),
                ('img_two', models.ImageField(upload_to='pics/')),
                ('img_three', models.ImageField(upload_to='pics/')),
                ('address', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('opencount', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('loction', models.TextField()),
                ('businesses', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Promoters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('loction', models.TextField()),
                ('businesses', models.TextField()),
            ],
        ),
    ]
