# Generated by Django 3.1.5 on 2021-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0002_business_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shortdescription',
            field=models.TextField(default='No data'),
        ),
    ]
